trigger:
  branches:
    include:
      - master
      - main
  paths:
    include:
      - Azure-DevOps/deploy-bicep.yml
      - .azuredevops/pipelines/test-deploy-bicep.yml
pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: SUB_FILE
    value: tests/deploy-bicep/subscription/main.bicep
  - name: SUB_PARAM_FILE
    value: tests/deploy-bicep/subscription/tst.bicepparam
  - name: GROUP_FILE
    value: tests/deploy-bicep/resource-group/main.bicep
  - name: GROUP_PARAM_FILE
    value: tests/deploy-bicep/resource-group/tst.bicepparam
  - name: SERVICE_CONNECTION
    value: sp-ado-reusable_workflows
  - name: SUB_RESOURCE_GROUP_NAME
    value: 'rg-deploy_sub-weu'
  - name: SUB_RESOURCE_GROUP_LOCATION
    value: 'westeurope'

stages:
  - stage: subscription_test
    displayName: Test Deployment on Subscription Level
    jobs:
      - job: deploy
        displayName: 'Deploy on Subscription Level'
        steps:
          - checkout: self
          - template: /Azure-DevOps/deploy-bicep.yml
            parameters:
              SERVICE_CONNECTION: ${{ variables.SERVICE_CONNECTION }}
              LOCATION: $(SUB_RESOURCE_GROUP_LOCATION)
              BICEP_FILE: $(SUB_FILE)
              BICEP_PARAMETERS_FILE: $(SUB_PARAM_FILE)

  - stage: resourcegroup_test
    displayName: Test Deployment on Resource Group Level
    dependsOn: subscription_test
    jobs:
      - job: deploy
        displayName: 'Deploy on Resource Group Level'
        steps:
          - checkout: self
          - template: /Azure-DevOps/deploy-bicep.yml
            parameters:
              SERVICE_CONNECTION: ${{ variables.SERVICE_CONNECTION }}
              RESOURCE_GROUP: $(SUB_RESOURCE_GROUP_NAME)
              BICEP_FILE: $(GROUP_FILE)
              BICEP_PARAMETERS_FILE: $(GROUP_PARAM_FILE)

  - stage: clean_up
    dependsOn: 
      - resourcegroup_test
    displayName: 'Clean Up'
    jobs:
      - job: clean_up
        displayName: 'Clean Up'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ variables.SERVICE_CONNECTION }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group delete \
                --name $RESOURCE_GROUP \
                --yes \
                --no-wait
            displayName: 'Delete Deployed Resources'
            env:
              RESOURCE_GROUP: $(SUB_RESOURCE_GROUP_NAME)