name: Test Versioning

on:
  push: 
    branches:
      - main
    paths:
      - 'GitHub/versioning.yml'
      - 'tests/version/**'

jobs:
  test:
    uses: MichielVanHerreweghe/reusable-workflows/.github/workflows/versioning.yml@main
    with:
        VERSION_FILE_PATH: 'tests/version/version.yml'